compositor: Drop vestigial queueing support
canonical/mir pull request #3237
Opened 2024-02-19 06:39 UTC by RAOF

We no longer need to be able to set a per-surface SwapInterval; that's handled client side. Likewise, we don't need to support submitting a queue of buffers to a surface; Wayland specifies mailbox¹ semantics.

Drop some of the infrastructure needed to support these features we no longer use anywhere (including QtMir)

¹: ie: framedropping

2024-02-19 10:14 UTC, AlanGriffiths requested changes
Looks sensible. It seems a shame to lose the flexibility, but we don't need it now.

2024-02-20 01:26 UTC, RAOF commented on src/server/compositor/multi_monitor_arbiter.h
> +    void submit_buffer(std::shared_ptr<graphics::Buffer> buffer);
Hm. I thought our resolution on that was:
* Pass `std::shared_ptr` (and `std::unique_ptr`) by value if ownership is definitely going to be taken
* Pass `std::shared_ptr<T>` by `const` reference if ownership is conditionally taken
* Pass by `T&` if ownership if definitely not taken.

I don't have particularly strong opinions, other than that `std::shared_ptr<T>&&` is weird.

2024-02-20 09:59 UTC, AlanGriffiths commented on src/server/compositor/multi_monitor_arbiter.h
> +    void submit_buffer(std::shared_ptr<graphics::Buffer> buffer);
Anyway, this is moot. We should be doing a `shared_ptr::swap()` in the implementation

2024-02-20 10:10 UTC, AlanGriffiths approved these changes
LGTM now

2024-02-20 11:07 UTC, merged