Feature/mircommon internal dev
canonical/mir pull request #3328
Opened 2024-04-11 20:45 UTC by mattkae

2024-04-25 15:56 UTC, AlanGriffiths requested changes
"Applications on the remote desktop can be run on the client" seems an odd commit comment for this PR. And I don't see why `run.sh` is added here? (Forgotten in an earlier PR perhaps?)

Anyway, needs clarification at least

2024-04-25 17:38 UTC, mattkae commented on tools/symbols_map_generator/run.sh
Whoops!

2024-04-25 17:39 UTC, mattkae commented
> "Applications on the remote desktop can be run on the client" seems an odd commit comment for this PR. And I don't see why `run.sh` is added here? (Forgotten in an earlier PR perhaps?)
> 
> Anyway, needs clarification at least

Multitasking, wrong copy and paste XD `run.sh` and `requirements.txt` were a bad merge

2024-04-26 11:29 UTC, AlanGriffiths commented on debian/control
> +Depends: libmircommon11 (= ${binary:Version}),
Hmm, `debian/changelog` for 2.16 says "mircommon ABI unchanged at 9". And...

```
$ git diff v2.16.4 -- debian/libmircommon10.install
diff --git a/debian/libmircommon10.install b/debian/libmircommon10.install
new file mode 100644
index 0000000000..5233fdfb45
--- /dev/null
+++ b/debian/libmircommon10.install
@@ -0,0 +1 @@
+usr/lib/*/libmircommon.so.10
```

So 10 is already new in 2.17

2024-04-26 11:40 UTC, AlanGriffiths requested changes
looks fine apart from the spurious .soname bump

2024-04-26 14:05 UTC, AlanGriffiths approved these changes

2024-04-26 15:03 UTC, merged