Build mir-libs for both core22 and core24
canonical/mir pull request #3364
Opened 2024-05-01 14:29 UTC by AlanGriffiths

2024-05-02 08:37 UTC, AlanGriffiths commented
The arm{hf,64} builds are failing elsewhere too. For example: https://github.com/canonical/mir/actions/runs/8880657717/job/24381211641?pr=3346

2024-05-02 11:44 UTC, AlanGriffiths commented
OK, so, from [one of the debug logs](https://productionresultssa12.blob.core.windows.net/actions-results/ad7f6c12-daf7-4d31-9cdd-8813f8eab517/workflow-job-run-a2abc2b0-fe48-5e72-f600-2127c587f4cf/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-02T11%3A44%3A02Z&sig=dkd4VO63pgG3N%2F5WYXeafAX8gE7pWarPjSooo%2FYjfZs%3D&sp=r&spr=https&sr=b&st=2024-05-02T11%3A33%3A57Z&sv=2021-12-02)...

```
2024-05-02T11:07:07.8240206Z ##[debug]echo "compatible-arch={2}" >> $GITHUB_OUTPUT
2024-05-02T11:07:07.8240972Z ##[debug]', inputs.snapcraft-channel, inputs.tools-channel, (fromJSON(env.ARCHES)[runner.arch] == inputs.architecture))
2024-05-02T11:07:07.8241693Z ##[debug]Evaluating format:
2024-05-02T11:07:07.8242030Z ##[debug]..Evaluating String:
2024-05-02T11:07:07.8242962Z ##[debug]..=> 'sudo snap install snapcraft --classic --channel {0}
2024-05-02T11:07:07.8243515Z ##[debug]sudo snap install review-tools --channel {1}
2024-05-02T11:07:07.8243914Z ##[debug]
2024-05-02T11:07:07.8244243Z ##[debug]echo "compatible-arch={2}" >> $GITHUB_OUTPUT
2024-05-02T11:07:07.8244650Z ##[debug]'
2024-05-02T11:07:07.8245020Z ##[debug]..Evaluating Index:
2024-05-02T11:07:07.8245361Z ##[debug]....Evaluating inputs:
2024-05-02T11:07:07.8245725Z ##[debug]....=> Object
2024-05-02T11:07:07.8246046Z ##[debug]....Evaluating String:
2024-05-02T11:07:07.8246401Z ##[debug]....=> 'snapcraft-channel'
2024-05-02T11:07:07.8246780Z ##[debug]..=> 'stable'
2024-05-02T11:07:07.8247112Z ##[debug]..Evaluating Index:
2024-05-02T11:07:07.8247438Z ##[debug]....Evaluating inputs:
2024-05-02T11:07:07.8247763Z ##[debug]....=> Object
2024-05-02T11:07:07.8248059Z ##[debug]....Evaluating String:
2024-05-02T11:07:07.8248395Z ##[debug]....=> 'tools-channel'
2024-05-02T11:07:07.8248729Z ##[debug]..=> 'stable'
2024-05-02T11:07:07.8249041Z ##[debug]..Evaluating Equal:
2024-05-02T11:07:07.8249370Z ##[debug]....Evaluating Index:
2024-05-02T11:07:07.8249707Z ##[debug]......Evaluating fromJSON:
2024-05-02T11:07:07.8252495Z ##[debug]........Evaluating Index:
2024-05-02T11:07:07.8252893Z ##[debug]..........Evaluating env:
2024-05-02T11:07:07.8253282Z ##[debug]..........=> Object
2024-05-02T11:07:07.8253643Z ##[debug]..........Evaluating String:
2024-05-02T11:07:07.8254010Z ##[debug]..........=> 'ARCHES'
2024-05-02T11:07:07.8256029Z ##[debug]........=> '{"X86": "i386", "X64": "amd64", "ARM": "armhf", "ARM64": "arm64"}'
2024-05-02T11:07:07.8269418Z ##[debug]......=> Object
2024-05-02T11:07:07.8269809Z ##[debug]......Evaluating Index:
2024-05-02T11:07:07.8270186Z ##[debug]........Evaluating runner:
2024-05-02T11:07:07.8270557Z ##[debug]........=> Object
2024-05-02T11:07:07.8270888Z ##[debug]........Evaluating String:
2024-05-02T11:07:07.8271241Z ##[debug]........=> 'arch'
2024-05-02T11:07:07.8271629Z ##[debug]......=> 'X64'
2024-05-02T11:07:07.8271956Z ##[debug]....=> 'amd64'
2024-05-02T11:07:07.8272272Z ##[debug]....Evaluating Index:
2024-05-02T11:07:07.8272615Z ##[debug]......Evaluating inputs:
2024-05-02T11:07:07.8272954Z ##[debug]......=> Object
2024-05-02T11:07:07.8273273Z ##[debug]......Evaluating String:
2024-05-02T11:07:07.8273629Z ##[debug]......=> 'architecture'
2024-05-02T11:07:07.8273968Z ##[debug]....=> 'armhf'
2024-05-02T11:07:07.8274270Z ##[debug]..=> false
2024-05-02T11:07:07.8275016Z ##[debug]=> 'sudo snap install snapcraft --classic --channel stable
2024-05-02T11:07:07.8275570Z ##[debug]sudo snap install review-tools --channel stable
2024-05-02T11:07:07.8275978Z ##[debug]
2024-05-02T11:07:07.8276305Z ##[debug]echo "compatible-arch=false" >> $GITHUB_OUTPUT
2024-05-02T11:07:07.8276737Z ##[debug]'
2024-05-02T11:07:07.8277160Z ##[debug]Result: 'sudo snap install snapcraft --classic --channel stable
2024-05-02T11:07:07.8277721Z ##[debug]sudo snap install review-tools --channel stable
2024-05-02T11:07:07.8278132Z ##[debug]
2024-05-02T11:07:07.8278452Z ##[debug]echo "compatible-arch=false" >> $GITHUB_OUTPUT
2024-05-02T11:07:07.8278843Z ##[debug]'
2024-05-02T11:07:07.8279291Z ##[debug]Loading env
2024-05-02T11:07:07.8286039Z ##[group]Run sudo snap install snapcraft --classic --channel stable
2024-05-02T11:07:07.8286668Z [36;1msudo snap install snapcraft --classic --channel stable[0m
2024-05-02T11:07:07.8287220Z [36;1msudo snap install review-tools --channel stable[0m
2024-05-02T11:07:07.8287643Z [36;1m[0m
2024-05-02T11:07:07.8287987Z [36;1mecho "compatible-arch=false" >> $GITHUB_OUTPUT[0m
2024-05-02T11:07:07.8340952Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2024-05-02T11:07:07.8341419Z env:
2024-05-02T11:07:07.8341802Z   ARCHES: {"X86": "i386", "X64": "amd64", "ARM": "armhf", "ARM64": "arm64"}
2024-05-02T11:07:07.8342297Z ##[endgroup]
2024-05-02T11:07:07.8396013Z ##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/4bef171f-cb02-438d-9f9b-698c3ac22172.sh
2024-05-02T11:07:25.2490361Z snapcraft 8.2.1 from Canonical** installed
2024-05-02T11:07:32.1626845Z review-tools 0.48+20240219-1530UTC from Canonical** installed
2024-05-02T11:07:32.1671624Z ##[debug]Set output compatible-arch = false
2024-05-02T11:07:32.1676066Z ##[debug]Finished: run
```

Looks like we're trying to build "armhf" on a "X64" runner which expects "amd64". (But I don't understand why yet)

2024-05-02 13:54 UTC, AlanGriffiths commented
OK, so running remote-building locally gets a readable log with:
```
:: + craftctl default
:: + git config --global --add safe.directory /build/snapcraft-mir-libs-76d1e6e890a8a2e4f6401d3bb6bf71c7/parts/mir/src
:: ++ git describe
:: ++ awk -F- '{ gsub(/^v/, "", $1); printf $1; if ($2) { printf "+dev" $2 "-" $3 } }'
:: fatal: No names found, cannot describe anything.
:: + craftctl set version=
:: +++ git describe
:: fatal: No names found, cannot describe anything.
:: ++ [[ '' =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
:: ++ echo devel
:: + craftctl set grade=devel
...

And _that_ is what is not working with remote build
Field 'version' was not adopted from metadata
```

2024-05-03 13:39 UTC, mattkae requested changes
Some minor nits/questions, but looks 99% good

2024-05-03 13:39 UTC, mattkae commented on snap/local/core24~snapcraft.yaml
> +name: mir-libs
Should this be renamed to `core24~snapcraft.yaml.in`?

2024-05-03 13:39 UTC, mattkae commented on snap/snapcraft.yaml
>    This snap contains the build environment necessary to build Mir display servers.
Should this be renamed to `core22~snapcraft.yaml.in`? And then we just move it to `snapcraft.yaml` if we have 22?

2024-05-03 13:39 UTC, mattkae commented on .github/workflows/snap.yml
> +        # fi
Should we create a ticket to re-add this once it's fixed?

2024-05-03 13:40 UTC, mattkae commented on .github/workflows/snap.yml
> +        # fi
Whoops! I see you have a PR already open for it, i take this back!

2024-05-03 13:40 UTC, mattkae commented on .github/workflows/snap.yml
> +        # fi
https://github.com/canonical/mir/pull/3369/

2024-05-03 13:50 UTC, mattkae commented on snap/snapcraft.yaml
>    This snap contains the build environment necessary to build Mir display servers.
Cool :+1:

2024-05-03 13:52 UTC, mattkae approved these changes
My nits were unimportant!

2024-05-03 14:36 UTC, merged