docs: augmenting the test plan to include 2.16 regressions
canonical/mir pull request #3397
Opened 2024-05-23 18:04 UTC by mattkae

## What's new?
- Added manual tests for a number of 2.16 regressions (see the [release page](https://github.com/canonical/mir/releases) for more info)

2024-05-24 10:37 UTC, AlanGriffiths requested changes
I have a problem with this approach: I don't think it is scalable to add manual testing for every bug we fix.

Only if we **cannot** automate a test **and** there is a likelyhood of a future regression should we consider adding manual testing

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +5. Test that `X11` apps can be started and can receive input when `XWayland` is supported:
I think using a specific compositor is appropriate here: e.g. the default `miral-app`

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +   [#2509](https://github.com/canonical/mir/issues/2509). To test:
I think this was a longstanding bug, not a 2.16 regression.

I don't doubt it needs testing, but this sort of arithmetic error should probably have a unit test.

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +   [#3024](https://github.com/canonical/mir/issues/3024).
I think this was a longstanding bug, not a 2.16 regression. Also, this should be reproducible on any of the free, or free trial, JetBrains tools

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +    3. Confirm that the output has the correctly rotated content
This is easier to test with 

```
miral-app -demo-server --screen-rotation
```
When you can "Rotate screen on Ctrl-Alt-<Arrow>"

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +  2. In the configuration, have a custom attribute, e.g. `snap-name` in the following example:
The only compositor that supports `snap-name` is Frame. And that gets its display configuration from the `display` snap configuration option.

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +    3. Enter `Ctrl + Alt + Backspace`
```suggestion
    3. "Send Key" `Ctrl + Alt + Backspace`
```

2024-05-24 10:37 UTC, AlanGriffiths commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +  [#3070](https://github.com/canonical/mir/issues/3070). To test:
This should probably be tested via test automation

2024-05-24 13:24 UTC, Saviq commented
> I have a problem with this approach: I don't think it is scalable to add manual testing for every bug we fix.
> 
> Only if we **cannot** automate a test **and** there is a likelyhood of a future regression should we consider adding manual testing

The idea is to record the scenarios we need to extend our testing with, and reduce the test plan as we bridge those gaps. Maybe it's a separate section, or document — things we know we can, and want to, automate? Or maybe they're just issues here, or on mir-ci?

2024-05-24 15:10 UTC, AlanGriffiths commented
> The idea is to record the scenarios we need to extend our testing with, and reduce the test plan as we bridge those gaps. Maybe it's a separate section, or document — things we know we can, and want to, automate? Or maybe they're just issues here, or on mir-ci?

I agree we should track those we don't (yet) have tests for. I don't agree they belong in the manual Mir test plan.

2024-05-28 11:18 UTC, mattkae commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +    This would be automated by https://github.com/canonical/mir-ci/issues/126.
Oops right! I will add that to the test description

2024-05-28 11:29 UTC, mattkae commented on doc/sphinx/how-to/how-to-test-mir-for-a-release.md
> +    This would be automated by https://github.com/canonical/mir-ci/issues/127.
True, the "multiple surfaces" bit was a hallucination on my part

2024-06-04 08:11 UTC, RAOF approved these changes
Yes, those are reasonable additions

2024-06-04 08:37 UTC, AlanGriffiths approved these changes
Sure

2024-06-06 11:12 UTC, merged