feature: resolving snap desktop files using app armor as the primary source
canonical/mir pull request #3426
Opened 2024-06-17 15:57 UTC by mattkae

## What's new?
- AppArmor is now the primary source of snap desktop files in the `DesktopFileManager`

2024-06-17 16:03 UTC, mattkae commented
Whoops, broke the tests. Will fix em soon...

2024-06-17 16:11 UTC, Saviq requested changes
You'll need to add a `libapparmor` build dependency to `debian/control`, and to `snap/snapcraft.yaml`.

2024-06-17 16:12 UTC, Saviq commented on src/server/frontend_wayland/desktop_file_manager.cpp
> +    // First, try to resolve the app armor profile
```suggestion
    // First, try to resolve the AppArmor profile
```

2024-06-17 21:25 UTC, mattkae commented
@Saviq What should I do about the apparmor dependency on Fedora and Alpine? :thinking: Should that be an optional dependency?

2024-06-18 04:43 UTC, Saviq commented
> @Saviq What should I do about the apparmor dependency on Fedora and Alpine? :thinking: Should that be an optional dependency?

If they're not there, yeah.

2024-06-18 05:28 UTC, Saviq commented
@mattkae Alpine does have it, BTW:

https://pkgs.alpinelinux.org/packages?name=apparmor

2024-06-18 11:14 UTC, mattkae commented
> @mattkae Alpine does have it, BTW:
> 
> https://pkgs.alpinelinux.org/packages?name=apparmor

Do you know if I'll need something else there too? https://github.com/canonical/mir/actions/runs/9552401270/job/26328915493?pr=3426

2024-06-18 12:47 UTC, Saviq commented
> Do you know if I'll need something else there too? https://github.com/canonical/mir/actions/runs/9552401270/job/26328915493?pr=3426

Yeah, you need to install it! :D

https://github.com/canonical/mir/blob/31ef0787e794f23e1eca415f575cd5859ec096b4/spread/build/alpine/task.yaml#L6-L34

2024-06-18 13:50 UTC, mattkae commented
> mir/spread/build/alpine/task.yaml

I have indeed added it, to no avail: https://github.com/canonical/mir/actions/runs/9566199163/job/26370892700?pr=3426 :cry: Is there _something else_ that I'm missing here?

2024-06-18 17:29 UTC, mattkae commented
> _lib_apparmor

That is what I have ;) https://github.com/canonical/mir/pull/3426/commits/918237ea740566a29b937d6a880fa8d246f1c6e8#diff-5f6d75408d28a1d92efc5968e0b1a34ee3c512d14427c514e56cd0b23290f52d

2024-06-20 06:02 UTC, RAOF reviewed
Looks sensible, but the build system parts could be cleaned up.

2024-06-20 12:44 UTC, Saviq approved these changes
Looks legit to me.

2024-06-20 12:44 UTC, Saviq commented on doc/sphinx/.readthedocs.yaml
> +  - libapparmor-dev
Since it's optional, let's skip it here.

2024-06-21 10:23 UTC, Saviq approved these changes
Yeah!

2024-06-21 10:55 UTC, merged