Demonstrate using the window decoration strategy
canonical/mir pull request #3459
Opened 2024-07-03 10:36 UTC by AlanGriffiths

2024-07-03 14:01 UTC, mattkae requested changes
A question!

2024-07-03 14:27 UTC, mattkae commented on examples/miral-shell/shell_main.cpp
> +};
Kk, just gonna test it out right now :smile:

2024-07-03 14:36 UTC, mattkae approved these changes
Working well for me! I tried all of the different configurations and it seemed to work.

2024-07-03 14:42 UTC, tarek-y-ismail approved these changes

2024-07-08 05:39 UTC, RAOF commented
Needs symbols fixes

2024-07-08 05:44 UTC, RAOF commented on examples/miral-shell/shell_main.cpp
> +        }()};
Yeah, immediately-executed lambdas are a way of turning C++ into an expression language. It can be particularly useful for `const` initialisation.

2024-07-08 11:09 UTC, AlanGriffiths commented
> Needs symbols fixes

I think main has that. Will rebase when back at keyboard

2024-07-08 22:58 UTC, merged