Fix LayerShellV1 flicker
canonical/mir pull request #3505
Opened 2024-07-23 14:49 UTC by tarek-y-ismail

closes #3450 

Removes a bunch of sizing related code that isn't quite obvious what it does when compared against the spec.

2024-07-23 21:41 UTC, AlanGriffiths commented
There are failing tests:

```
2024-07-23T14:57:49.4182258Z [  FAILED  ] LayerSurfaceTest.gets_configured_with_supplied_size_even_when_anchored_to_edges
...
2024-07-23T14:57:49.4369420Z [  FAILED  ] Anchor/LayerSurfaceLayoutTest.is_initially_positioned_correctly_for_anchor/3, where GetParam() = Anchor{bottom}, Margin{l: 6, r: 9, t: 12, b: 15} (30 ms)
...
```

2024-07-24 08:24 UTC, tarek-y-ismail commented
Seems like the second "fix" breaks more tests than it fixes...

2024-08-05 11:44 UTC, AlanGriffiths commented
As discussed (in the bug) I don't think this addresses the problem

2024-08-22 16:11 UTC, AlanGriffiths requested changes

2024-08-22 16:11 UTC, AlanGriffiths commented on src/server/frontend_wayland/layer_shell_v1.cpp
>      }
OK, so you asked why there was a queue, and this error answers: we want to error if the serial doesn't match a pending configure.

But I think the existing logic is wrong anyway:

1.It assumes that serial never overflows; and,
2. It processes stale acks (that you do fix)

So I think that

1. The queue should stay; and,
2. The logic should be something like...

```c++
    auto const acked_event = std::find_if(
        std::begin(inflight_configures),
        std::end(inflight_configures),
        [serial](auto& p) { return p.serial == serial; });

    if (acked_event == std::end(inflight_configures))
    {
        BOOST_THROW_EXCEPTION(std::runtime_error(
            "Could not find acked configure with serial " + std::to_string(serial)));
    }

    auto const acked_configure_size = acked_event->second;

    inflight_configures.erase(std::begin(inflight_configures), ++acked_event);
    
    if (!inflight_configures.empty())
    {
        // If a stale configure has been acked, we do no more
        return;
    }
```

2024-08-23 09:55 UTC, AlanGriffiths approved these changes
WFM

2024-08-23 10:10 UTC, merged