Energy efficiency
canonical/mir pull request #3633
Opened 2024-10-14 11:38 UTC by AlanGriffiths

2024-10-16 10:02 UTC, tarek-y-ismail commented
Again, some notes  that you're free to pick from.

It could be mentioned that the use of file descriptors to wait for events/data/input/etc... improves efficiency by allowing the CPU to idle to lower clock speeds and maybe turn off other cores (depends on other things running of course). 

Another thing that can be mentioned is that our usage of C++ is a deliberate choice to balance runtime performance and development speed versus other interpreted (Python) or compiled +  GC langauges (Go, Java).

2024-10-16 11:07 UTC, Saviq requested changes
Please add to `explanation.md` and to the TOC.

2024-10-16 12:55 UTC, AlanGriffiths commented on doc/sphinx/explanation/energy-efficiency.md
> +At the time of writing (October 2024) Mir has not implemented this optimisation.
By "full surface" you mean display buffer?

2024-10-16 13:48 UTC, AlanGriffiths commented
> Please add to `explanation.md` and to the TOC.

I've stacked this on top of `performance` to avoid merge conflicts

2024-10-16 15:59 UTC, Saviq commented on doc/sphinx/explanation/energy-efficiency.md
> +At the time of writing (October 2024) Mir has not implemented this optimisation.
At least in the screencopy sense, we report on damage per client surface (not deeper than that).

Does damage even matter in the composition sense? We're asking the GPU to do the composition on client-supplied buffers, would we even communicate the damage there?

It would matter for a software renderer, but for a GL one?

2024-10-16 16:16 UTC, AlanGriffiths commented on doc/sphinx/explanation/energy-efficiency.md
> +At the time of writing (October 2024) Mir has not implemented this optimisation.
Yes, it matters: a while back Firefox was submitting buffers with damage hints, but only the pixels corresponding to the damage were supplied (which was a Firefox bug). Because we don't pass on the damage info the results were wrong. (This shows that other compositors do pass on the damage hints)

2024-10-18 08:59 UTC, Saviq approved these changes
And this one, too :)

2024-10-18 09:40 UTC, merged