New attached windows need to be placed
canonical/mir pull request #3676
Opened 2024-11-19 10:02 UTC by AlanGriffiths

Alternative to #3675

2024-11-19 19:49 UTC, mattkae requested changes
This does not fix the problem that I was having with `cosmic-bg` because `LayerSurfaceV1::configure()` happens before `BasicWindowManager::place_new_surface()`. The surface has not yet been placed when we send the configure event

2024-11-21 12:14 UTC, AlanGriffiths commented
That sequence seems ... wrong. But I see it too:
```
[ 635173.015]  -> wl_compositor#6.create_surface(new id wl_surface#11)
[ 635173.030]  -> zwlr_layer_shell_v1#8.get_layer_surface(new id zwlr_layer_surface_v1#12, wl_surface#11, wl_output#3, 0, "wallpaper")
[ 635173.045]  -> zwlr_layer_surface_v1#12.set_anchor(15)
[ 635173.052]  -> zwlr_layer_surface_v1#12.set_exclusive_zone(-1)
[ 635173.058]  -> zwlr_layer_surface_v1#12.set_keyboard_interactivity(0)
[ 635173.066]  -> wl_surface#11.commit()
[ 635173.073]  -> wp_viewporter#9.get_viewport(new id wp_viewport#13, wl_surface#11)
[ 635173.102]  -> wp_fractional_scale_manager_v1#10.get_fractional_scale(new id wp_fractional_scale_v1#14, wl_surface#11)
[ 635173.788] zwlr_layer_surface_v1#12.configure(9, 0, 0)
[ 635173.807] zwlr_layer_surface_v1#12.configure(10, 1600, 900)
```

2024-11-21 12:55 UTC, AlanGriffiths commented
> The surface has not yet been placed when we send the configure event

Fixed now

2024-11-21 14:01 UTC, mattkae commented
This makes it not crash :+1:  But it doesn't make it work for `cosmic-bg` unlike my other PR. I'll investigate and let you know why. They appear the same on the surface

2024-11-22 21:18 UTC, mattkae commented
I have fixed it with the latest commit @AlanGriffiths:

![image](https://github.com/user-attachments/assets/f21d94c9-f7e4-4aff-84dd-8d0b2319a4a2)

2024-11-22 21:50 UTC, Saviq commented
> 32 - wlcs.Anchor/LayerSurfaceLayoutTest.* (Failed)

:)

2024-11-24 17:58 UTC, AlanGriffiths commented on src/server/frontend_wayland/layer_shell_v1.cpp
> +        : client_size.pending().width;
Isn't `value_or()` clearer?

2024-11-25 10:06 UTC, AlanGriffiths commented on src/server/frontend_wayland/layer_shell_v1.cpp
> +        : client_size.pending().width;
Ignore me. The result is a `std::optional`

2024-11-25 16:32 UTC, AlanGriffiths commented
Oops! Pulled the rug out of another corner

2024-11-25 17:18 UTC, AlanGriffiths commented
@mattkae I'm not sure what the essential behaviour you want from https://github.com/canonical/mir/pull/3676/commits/9247cc95c8c4a981dc1a43ac2b3ccb34653511d8 is. I've fixed the stuff it broke, but now not sure if the last two commits are even changing anything. (A shame you couldn't add a test)

2024-11-26 12:10 UTC, AlanGriffiths commented
Not sure why (but I never tracked down the cause) this also seems to fix some intermittent yambar crashing

2024-11-26 15:03 UTC, mattkae approved these changes
Working well for me now :+1:

2024-11-26 15:48 UTC, merged