Extract rendering strategy for decorations
canonical/mir pull request #3706
Opened 2024-12-19 14:13 UTC by AlanGriffiths

This extracts the generic rendering integration from the default "strategy" for rendering

2024-12-19 14:14 UTC, AlanGriffiths commented
Note that while this is a stable intermediate form (and can be merged), it doesn't extract everything that should be customised by a "decoration strategy": There's still two customisation points needed: the "static geometry", and the button placement

2024-12-20 12:34 UTC, mattkae requested changes
Some initial feedback but it looks like a good move to me!

2024-12-20 13:58 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +        if (boost::filesystem::exists(path))
This is existing code I didn't aim to rework for this PR

2024-12-20 13:58 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +                if (boost::filesystem::exists(full_font_path))
This is existing code I didn't aim to rework for this PR

2024-12-20 13:58 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +        : 0;
This is existing code I didn't aim to rework for this PR

2024-12-20 13:58 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +        mir::log_warning("FreeType not initialized");
This is existing code I didn't aim to rework for this PR

2024-12-20 13:58 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +        mir::log_warning("%s", error.what());
This is existing code I didn't aim to rework for this PR

2024-12-20 14:00 UTC, AlanGriffiths commented on src/server/shell/decoration/renderer_default.cpp
> +}
This just wires things up. It goes away in the follow-up PR

2024-12-20 15:33 UTC, mattkae approved these changes
Approving since this is all preexisting :)

2024-12-20 16:22 UTC, merged